Open Judge System/Web/OJS.Web/ViewModels/Home/Index/HomeContestViewModel.cs
namespace OJS.Web.ViewModels.Home.Index
{
    using System;
    using System.Linq.Expressions;
    using OJS.Data.Models;

    public class HomeContestViewModel
    {
        public static Expression<Func<Contest, HomeContestViewModel>> FromContest
        {
            get
            {
                return contest => new HomeContestViewModel
                {
                    Id = contest.Id,
                    Name = contest.Name,
                    StartTime = contest.StartTime,
                    EndTime = contest.EndTime,
                };
            }
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public DateTime? StartTime { get; set; }

        public DateTime? EndTime { get; set; }
    }
}

Open Judge System/Web/OJS.Web/ViewModels/Home/Index/IndexViewModel.cs
namespace OJS.Web.ViewModels.Home.Index
{
    using System.Collections.Generic;

    public class IndexViewModel
    {
        public IEnumerable<HomeContestViewModel> ActiveContests { get; set; }

        public IEnumerable<HomeContestViewModel> PastContests { get; set; }

        public IEnumerable<HomeContestViewModel> FutureContests { get; set; }
    }
}

Open Judge System/Web/OJS.Web/Controllers/HomeController.cs
namespace OJS.Web.Controllers
{
    using System.Linq;
    using System.Text;
    using System.Web.Mvc;

    using OJS.Data;
    using OJS.Web.ViewModels.Home.Index;

    public class HomeController : BaseController
    {
        public HomeController(IOjsData data)
            : base(data)
        {
        }

        public ActionResult Index()
        {
            var indexViewModel = new IndexViewModel
            {
                ActiveContests = this.Data.Contests.AllActive()
                    .OrderByDescending(x => x.StartTime)
                    .Select(HomeContestViewModel.FromContest)
                    .ToList(),
                FutureContests = this.Data.Contests.AllFuture()
                    .OrderBy(x => x.StartTime)
                    .Select(HomeContestViewModel.FromContest)
                    .ToList(),
                PastContests = this.Data.Contests.AllPast()
                    .OrderByDescending(x => x.StartTime)
                    .Select(HomeContestViewModel.FromContest)
                    .Take(5)
                    .ToList()
            };

            return this.View(indexViewModel);
        }

        /// <summary>
        /// Gets the robots.txt file.
        /// </summary>
        /// <returns>Returns a robots.txt file.</returns>
        [HttpGet]
        [OutputCache(Duration = 3600)]
        public FileResult RobotsTxt()
        {
            var robotsTxtContent = new StringBuilder();
            robotsTxtContent.AppendLine("User-Agent: *");
            robotsTxtContent.AppendLine("Allow: /");

            return this.File(Encoding.ASCII.GetBytes(robotsTxtContent.ToString()), "text/plain");
        }
    }
}

Open Judge System/Web/OJS.Web/Controllers/NewsController.cs
namespace OJS.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;

    using OJS.Data;
    using OJS.Web.ViewModels.News;

    using Resource = Resources.News;

    public class NewsController : BaseController
    {
        public NewsController(IOjsData data)
            : base(data)
        {
        }

        public ActionResult All(int id = 1, int pageSize = 10)
        {
            var newsCount = this.Data.News.All().Count(x => x.IsVisible);

            IEnumerable<NewsViewModel> news;
            int page = 0;
            int pages = 0;

            if (newsCount == 0)
            {
                news = new List<NewsViewModel>();
            }
            else
            {
                if (newsCount % pageSize == 0)
                {
                    pages = newsCount / pageSize;
                }
                else
                {
                    pages = (newsCount / pageSize) + 1;
                }

                if (id < 1)
                {
                    id = 1;
                }
                else if (id > pages)
                {
                    id = pages;
                }

                if (pageSize < 1)
                {
                    pageSize = 10;
                }

                page = id;

                news = this.Data.News.All()
                    .Where(x => x.IsVisible)
                    .OrderByDescending(x => x.CreatedOn)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize)
                    .Select(NewsViewModel.FromNews)
                    .ToList();
            }

            var allNewsModel = new AllNewsViewModel
            {
                AllNews = news,
                CurrentPage = page,
                PageSize = pageSize,
                AllPages = pages
            };

            return this.View(allNewsModel);
        }

        public ActionResult Selected(int id = 1)
        {
            var currentNews = this.Data.News.GetById(id);

            if (currentNews == null || currentNews.IsDeleted)
            {
                throw new HttpException((int)HttpStatusCode.NotFound, Resource.Views.Selected.Invalid_news_id);
            }

            var previousNews =
                this.Data.News.All()
                    .OrderByDescending(x => x.Id)
                    .FirstOrDefault(x => x.Id < currentNews.Id && x.IsVisible && !x.IsDeleted)
                ?? this.Data.News.All().OrderByDescending(x => x.Id).First(x => x.IsVisible && !x.IsDeleted);

            var nextNews =
                this.Data.News.All()
                    .OrderBy(x => x.Id)
                    .FirstOrDefault(x => x.Id > currentNews.Id && x.IsVisible && !x.IsDeleted)
                ?? this.Data.News.All().OrderBy(x => x.Id).First(x => x.IsVisible && !x.IsDeleted);

            var newsContentViewModel = new SelectedNewsViewModel
            {
                Id = currentNews.Id,
                Title = currentNews.Title,
                Author = currentNews.Author,
                Source = currentNews.Source,
                TimeCreated = currentNews.CreatedOn,
                Content = currentNews.Content,
                PreviousId = previousNews.Id,
                NextId = nextNews.Id
            };

            return this.View(newsContentViewModel);
        }

        [ChildActionOnly]
        public ActionResult LatestNews(int newsCount = 5)
        {
            var latestNews =
                this.Data.News.All()
                    .OrderByDescending(x => x.CreatedOn)
                    .Where(x => x.IsVisible && !x.IsDeleted)
                    .Select(SelectedNewsViewModel.FromNews)
                    .Take(newsCount)
                    .ToList();

            return this.PartialView("_LatestNews", latestNews);
        }
    }
}

Open Judge System/Web/OJS.Web/Views/Home/Index.cshtml
@using Resource = Resources.Home.Views.Index

@model OJS.Web.ViewModels.Home.Index.IndexViewModel

@{
    ViewBag.Title = Resource.Title;
}

<div class="jumbotron">
    <div class="row">
        <div class="pull-left col-md-6">
            <h1>@Resource.Project_title</h1>
            <p class="lead">@Resource.Project_subtitle</p>
            @if (Model.ActiveContests.Any())
            {
                <div class="fb-like" data-href="http://bgcoder.com" data-send="true" data-width="450" data-show-faces="true" data-colorscheme="dark"></div>
            }
        </div>
        <div class="pull-right col-md-6">
            @if (Model.ActiveContests.Any())
            {
                <h2>@Resource.Active_contests</h2>
                <table class="table table-hover">
                    @if (Model.ActiveContests.Count() <= 3)
                    {
                        foreach (var contest in Model.ActiveContests)
                        {
                            var hoursRemaining = (int)((contest.EndTime.Value - DateTime.Now)).TotalHours;
                            var minutesRemaining = (contest.EndTime.Value - DateTime.Now).Minutes;
                            <tr>
                                <td>
                                    <a href="@ContestsHelper.GetUrl(contest.Id, contest.Name)"><strong>@contest.Name</strong></a><br />
                                    @{
                            string remainingTimeMessage =
                                string.Format(Resource.Remaining_time, hoursRemaining, hoursRemaining != 1 ?
                                    Resource.Hours : Resource.Hour, minutesRemaining);
                                    }
                                    <small>@remainingTimeMessage</small>
                                </td>

                                <td><a class="btn btn-primary pull-left" href="@ContestsHelper.GetUrl(contest.Id, contest.Name)">@Resource.Participate</a></td>
                            </tr>
                        }
                    }
                    else
                    {
                        foreach (var contest in Model.ActiveContests)
                        {
                            <tr>
                                <td class="">
                                    <a href="@ContestsHelper.GetUrl(contest.Id, contest.Name)">@contest.Name</a>
                                </td>
                            </tr>
                        }
                    }
                </table>
            }
            else
            {
                <div class="fb-like" data-href="http://www.facebook.com/BGCoder" data-colorscheme="dark" data-width="380" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
            }
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>@Resource.News</h2>
        @{Html.RenderAction("LatestNews", "News", new { newsCount = 4 });}
    </div>
    <div class="col-md-4">
        <h2>@Resource.Previous_contests</h2>
        @if (!Model.PastContests.Any())
        {
            <p>@Resource.No_previous_contests</p>
        }
        else
        {
            <table class="table table-hover">
                @foreach (var contest in Model.PastContests)
                {
                    <tr>
                        <td>
                            <a href="@ContestsHelper.GetUrl(contest.Id, contest.Name)">@contest.Name</a>
                            <p class="text-right">@Resource.Ended: @contest.EndTime.ToString()</p>
                        </td>
                    </tr>
                }
            </table>
        }
        <p class="pull-right"><a class="btn btn-default" href="/Contests/">@Resource.See_more &raquo;</a></p>
        @if (User.IsAdmin())
        {
            <p class="pull-left"><a class="btn btn-primary" href="/Administration/Contests">@Resource.Administration &raquo;</a></p>
        }
    </div>
    <div class="col-md-4">
        <h2>@Resource.Upcoming_contests</h2>
        @if (!Model.FutureContests.Any())
        {
            <p>@Resource.No_upcoming_contests</p>
        }
        else
        {
            <table class="table table-hover">
                @foreach (var contest in Model.FutureContests)
                {
                    <tr>
                        <td>
                            <a href="@ContestsHelper.GetUrl(contest.Id, contest.Name)">@contest.Name</a>
                            <p class="text-right">@Resource.Starts: @contest.StartTime.ToString()</p>
                        </td>
                    </tr>
                }
            </table>
            <p class="pull-right"><a class="btn btn-default" href="/Contests/">@Resource.See_more &raquo;</a></p>
        }
        @if (User.IsAdmin())
        {
            <p class="pull-left"><a class="btn btn-primary" href="/Administration/Contests">@Resource.Administration &raquo;</a></p>
        }
    </div>
</div>